# Generated by Django 6.0.2 on 2026-02-27 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugPermitInfo',
            fields=[
                ('item_seq', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='품목기준코드')),
                ('item_name', models.TextField(verbose_name='제품명')),
                ('item_eng_name', models.TextField(blank=True, null=True, verbose_name='제품명(영문)')),
                ('entp_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='업체명')),
                ('main_ingr_eng', models.TextField(blank=True, null=True, verbose_name='주성분(영문)')),
                ('main_ingr_kor', models.TextField(blank=True, null=True, verbose_name='주성분(한글)')),
                ('etc_otcc_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='전문/일반')),
                ('source_updated_at', models.DateField(blank=True, null=True, verbose_name='허가일자')),
                ('last_synced_at', models.DateTimeField(auto_now=True, verbose_name='시스템동기화일')),
            ],
            options={
                'verbose_name': '의약품 허가 정보',
                'verbose_name_plural': '의약품 허가 정보 목록',
                'db_table': 'drug_permit_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EYakInfo',
            fields=[
                ('item_seq', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='품목기준코드')),
                ('item_name', models.TextField(verbose_name='제품명')),
                ('entp_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='업체명')),
                ('efficacy', models.TextField(blank=True, null=True, verbose_name='효능')),
                ('use_method', models.TextField(blank=True, null=True, verbose_name='사용법')),
                ('precautions', models.TextField(blank=True, null=True, verbose_name='주의사항')),
                ('interaction', models.TextField(blank=True, null=True, verbose_name='상호작용')),
                ('side_effects', models.TextField(blank=True, null=True, verbose_name='부작용')),
                ('item_image', models.URLField(blank=True, max_length=500, null=True, verbose_name='제품이미지URL')),
                ('source_updated_at', models.DateField(blank=True, null=True, verbose_name='식약처수정일')),
                ('last_synced_at', models.DateTimeField(auto_now=True, verbose_name='시스템동기화일')),
            ],
            options={
                'verbose_name': 'e약은요 상세 정보',
                'verbose_name_plural': 'e약은요 상세 정보 목록',
                'db_table': 'eyak_info',
            },
        ),
        migrations.CreateModel(
            name='UnifiedDrugInfo',
            fields=[
                ('item_seq', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='품목기준코드')),
                ('item_name', models.TextField(db_index=True, verbose_name='제품명')),
                ('entp_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='업체명')),
                ('etc_otcc_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='전문/일반')),
                ('main_ingr_eng', models.TextField(blank=True, null=True, verbose_name='주성분(영문)')),
                ('main_ingr_kor', models.TextField(blank=True, null=True, verbose_name='주성분(한글)')),
                ('efficacy', models.TextField(blank=True, null=True, verbose_name='효능')),
                ('use_method', models.TextField(blank=True, null=True, verbose_name='사용법')),
                ('precautions', models.TextField(blank=True, null=True, verbose_name='주의사항')),
                ('interaction', models.TextField(blank=True, null=True, verbose_name='상호작용')),
                ('side_effects', models.TextField(blank=True, null=True, verbose_name='부작용')),
                ('item_image', models.URLField(blank=True, max_length=500, null=True, verbose_name='제품이미지URL')),
                ('source_updated_at', models.DateField(blank=True, null=True, verbose_name='허가일/수정일')),
                ('last_synced_at', models.DateTimeField(auto_now=True, verbose_name='시스템동기화일')),
            ],
            options={
                'verbose_name': '통합 의약품 정보',
                'verbose_name_plural': '통합 의약품 정보 목록',
                'db_table': 'unified_drug_info',
            },
        ),
        migrations.CreateModel(
            name='DurMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dur_seq', models.CharField(blank=True, max_length=50, null=True, verbose_name='DUR일련번호')),
                ('dur_type', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='금기유형')),
                ('type_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='금기유형명')),
                ('ingr_code', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='성분코드')),
                ('ingr_kor_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='성분명(국문)')),
                ('ingr_eng_name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='성분명(영문)')),
                ('form_name', models.TextField(blank=True, null=True, verbose_name='제형')),
                ('mix_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='단일/복합')),
                ('mix_ingr', models.TextField(blank=True, null=True, verbose_name='복합성분정보')),
                ('ori_ingr', models.TextField(blank=True, null=True, verbose_name='원문성분정보')),
                ('mixture_ingr_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='병용금기성분코드')),
                ('mixture_ingr_kor_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='병용금기성분명(국문)')),
                ('mixture_ingr_eng_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='병용금기성분명(영문)')),
                ('mixture_mix_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='병용단일/복합')),
                ('mixture_class', models.CharField(blank=True, max_length=255, null=True, verbose_name='병용약효분류')),
                ('mixture_ori', models.TextField(blank=True, null=True, verbose_name='병용원문정보')),
                ('grade', models.CharField(blank=True, max_length=50, null=True, verbose_name='금기등급')),
                ('max_qty', models.CharField(blank=True, max_length=100, null=True, verbose_name='최대투여량')),
                ('max_dosage_term', models.CharField(blank=True, max_length=100, null=True, verbose_name='최대투여기간')),
                ('age_base', models.CharField(blank=True, max_length=100, null=True, verbose_name='기준연령')),
                ('effect_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='효능코드')),
                ('sers_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='효능군명')),
                ('critical_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='핵심주의값(통합)')),
                ('prohbt_content', models.TextField(blank=True, null=True, verbose_name='금기내용')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('class_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='효능군/계열')),
                ('notification_date', models.DateField(blank=True, null=True, verbose_name='공고일자')),
                ('del_yn', models.CharField(default='정상', max_length=10, verbose_name='삭제여부')),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dur_master',
                'indexes': [models.Index(fields=['dur_type', 'ingr_code'], name='dur_master_dur_typ_4c5a20_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_medications', models.TextField(blank=True, null=True, verbose_name='복용 중인 약')),
                ('allergies', models.TextField(blank=True, null=True, verbose_name='알러지')),
                ('chronic_diseases', models.TextField(blank=True, null=True, verbose_name='기저질환')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 프로필',
                'verbose_name_plural': '사용자 프로필 목록',
                'db_table': 'user_profile',
            },
        ),
    ]
