name: Call Project Board Sync

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  call-project-board-sync:
    uses: DJAeun/common-actions/.github/workflows/project-board-sync.yml@main
    secrets: inherit
