name: Call Secret Scan

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  call-secret-scan:
    uses: DJAeun/common-actions/.github/workflows/secret-scan.yml@main
    secrets: inherit
