-- Supabase Complete Schema for AntiGravity Project (KCD 9th Integrated)

-- ==========================================
-- 1. Extensions & Settings
-- ==========================================
-- Enable pg_trgm for fast text similarity search (used in disease/drug search)
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- ==========================================
-- 2. KCD 질병 정보 테이블 (KCD 9차 개정판 반영)
-- ==========================================
CREATE TABLE IF NOT EXISTS public.kcd_info (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kcd_code VARCHAR(20) NOT NULL UNIQUE, -- 질병 코드 (예: A00.0)
    kcd_name_kor TEXT NOT NULL, -- 질병 한글 명칭
    kcd_name_eng TEXT, -- 질병 영문 명칭
    created_at TIMESTAMP
    WITH
        TIME ZONE DEFAULT NOW()
);

-- 트리그램 인덱스 (한글/영문 검색 최적화)
CREATE INDEX IF NOT EXISTS idx_kcd_name_kor_trgm ON public.kcd_info USING gin (kcd_name_kor gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_kcd_name_eng_trgm ON public.kcd_info USING gin (kcd_name_eng gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_kcd_code ON public.kcd_info (kcd_code);

-- ==========================================
-- 3. DUR 마스터 데이터 테이블
-- ==========================================
CREATE TABLE IF NOT EXISTS public.dur_master (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dur_seq VARCHAR(50),
    dur_type VARCHAR(50) NOT NULL,
    type_name VARCHAR(50),
    ingr_code VARCHAR(20) NOT NULL,
    ingr_kor_name VARCHAR(255) NOT NULL,
    ingr_eng_name VARCHAR(255),
    form_name TEXT,
    mix_type VARCHAR(50),
    mix_ingr TEXT,
    ori_ingr TEXT,
    mixture_ingr_code VARCHAR(20),
    mixture_ingr_kor_name VARCHAR(255),
    mixture_ingr_eng_name VARCHAR(255),
    mixture_mix_type VARCHAR(50),
    mixture_class VARCHAR(255),
    mixture_ori TEXT,
    grade VARCHAR(50),
    max_qty VARCHAR(100),
    max_dosage_term VARCHAR(100),
    age_base VARCHAR(100),
    effect_code VARCHAR(50),
    sers_name VARCHAR(255),
    critical_value VARCHAR(255),
    prohbt_content TEXT,
    remark TEXT,
    class_name VARCHAR(255),
    notification_date DATE,
    del_yn VARCHAR(10) DEFAULT '정상',
    last_synced_at TIMESTAMP
    WITH
        TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_dur_master_ingr_eng ON public.dur_master (ingr_eng_name);

CREATE INDEX IF NOT EXISTS idx_dur_master_ingr_kor ON public.dur_master (ingr_kor_name);

-- ==========================================
-- 4. 통합 의약품 상세 정보 테이블
-- ==========================================
CREATE TABLE IF NOT EXISTS public.unified_drug_info (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_seq VARCHAR(50) NOT NULL UNIQUE,
    item_name VARCHAR(255) NOT NULL,
    entp_name VARCHAR(255),
    etc_otcc_name VARCHAR(50),
    main_ingr_eng TEXT,
    main_ingr_kor TEXT,
    efficacy TEXT,
    use_method TEXT,
    precautions TEXT,
    interaction TEXT,
    side_effects TEXT,
    item_image TEXT,
    source_updated_at TIMESTAMP
    WITH
        TIME ZONE,
        last_synced_at TIMESTAMP
    WITH
        TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_unified_drug_name ON public.unified_drug_info (item_name);

CREATE INDEX IF NOT EXISTS idx_unified_efficacy_trgm ON public.unified_drug_info USING gin (efficacy gin_trgm_ops);

-- ==========================================
-- 5. 의약품 허가 기본 정보 테이블
-- ==========================================
CREATE TABLE IF NOT EXISTS public.drug_permit_info (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_seq VARCHAR(50) NOT NULL UNIQUE,
    item_name VARCHAR(255) NOT NULL,
    item_eng_name VARCHAR(255),
    entp_name VARCHAR(255),
    main_ingr_eng TEXT,
    main_ingr_kor TEXT,
    etc_otcc_name VARCHAR(50),
    source_updated_at TIMESTAMP
    WITH
        TIME ZONE,
        last_synced_at TIMESTAMP
    WITH
        TIME ZONE DEFAULT NOW()
);

-- ==========================================
-- 6. 사용자 프로필 및 개인 의료 정보
-- ==========================================
CREATE TABLE IF NOT EXISTS public.user_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL UNIQUE, -- Supabase Auth의 user_id 연동
    current_medications TEXT, -- 현재 복용 중인 약물
    allergies TEXT, -- 알레르기 정보
    chronic_diseases TEXT, -- 만성 질환 정보
    applied_allergies TEXT, -- 현재 적용 중인 알레르기 정보
    applied_chronic_diseases TEXT, -- 현재 적용 중인 기저질환 정보
    food_allergy_detail TEXT, -- 음식 알레르기 세부정보
    is_pregnant BOOLEAN DEFAULT FALSE, -- 임신 여부
    main_ingr_eng TEXT, -- 복용 약물의 성분 (시스템 분석용)
    updated_at TIMESTAMP
    WITH
        TIME ZONE DEFAULT NOW()
);

-- ==========================================
-- 7. 증상 검색 엔진 캐시 테이블
-- ==========================================
CREATE TABLE IF NOT EXISTS public.search_cache (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    query_text TEXT NOT NULL UNIQUE, -- 사용자 검색 질의
    category VARCHAR(100), -- 증상 카테고리
    fda_data JSONB, -- FDA API 분석 결과
    dur_data JSONB, -- DUR 매핑 결과
    final_answer TEXT, -- AI 최종 처방 가이드
    recommended_ingredients JSONB, -- 추천 성분 리스트
    created_at TIMESTAMP
    WITH
        TIME ZONE DEFAULT NOW()
);
